apiVersion: extensions/v1beta1
kind: Pod
metadata:
  labels:
    app: sleep-pod
  name: sleep-pod
  namespace: default
spec:
  containers:
  - image: centos:latest
    imagePullPolicy: Always
    name: app
    command: ['/bin/bash']
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30